<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-IntegrationHub.Workers-b9a55ef0-f63d-4039-8b16-3dfe8ea459a0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.NetCore" Version="1.8.14" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IntegrationHub.Shared\IntegrationHub.Shared.csproj" />
    <ProjectReference Include="..\IntegrationHub.Infrastructure\IntegrationHub.Infrastructure.csproj" />
    <ProjectReference Include="..\IntegrationHub.Application\IntegrationHub.Application.csproj" />
  </ItemGroup>
</Project>
